### ISSUE TITLE
still getting Please enable Billplz XSignature even settings are on.

### ISSUE THREAD

**Issue by aifaiz** [Billplz/Billplz-for-PrestaShop-1.7#2]
hi bro. this is nice! however im getting the same error `Please enable Billplz XSignature Payment Completion` even the settings are enabled in my account.
.
payment went tough. account deducted. return page are giving same error.
.
my ps version: 1.7.4.2

**Comment by wzul** [comment]
Hi.

Make sure you have copied the X Signature into the Billplz for Prestashop settings.

Please be noted that using Prestashop 1.7 is not recommended

**Comment by aifaiz** [comment]
hi bro. yep. the X Signature has been copied properly.
.
this 

> Please be noted that using Prestashop 1.7 is not recommended

what do you mean? im using prestashop 1.7.4.2 its the latest version. 
its not supported?

**Comment by wzul** [comment]
Please email details (Prestashop and Billplz) to wan@billplz.com for further troubleshooting on this matter

> what do you mean? im using prestashop 1.7.4.2 its the latest version.
> its not supported?

Yes. It has issue with Callback request which preventing the callback to update the order
