### ISSUE TITLE
Cannot install module with Prestashop 1.7.8.11

### ISSUE THREAD

**Issue by faisalds** [Billplz/Billplz-for-PrestaShop-1.7#7]
It cannot install with the latest Prestashop module 1.7.8.11.

**Comment by yiedpozi** [comment]
Thank you for letting us know. We will investigate further and keep you updated.

**Comment by faisalds** [comment]
Thank you for the prompt reply

**Comment by yiedpozi** [comment]
@faisalds From our end, we able to install this module on Prestashop version 1.7.8.11. May I know what kind of error you encountered during the installation?

If you are able to install the module but the payment method is not displayed on your checkout page, please ensure to set the `Currency Restrictions` for `Billplz` payment method in your Prestashop store.

Check out our README on [how to set `Currency Restrictions`](https://github.com/Billplz/Billplz-for-PrestaShop-1.7?tab=readme-ov-file#set-currency-restriction).

**Comment by faisalds** [comment]
Here what I got when upload the module

Exception:
This file does not seem to be a valid module zip

  at src/Adapter/Module/ModuleZipManager.php:139
  at PrestaShop\PrestaShop\Adapter\Module\ModuleZipManager->getName()
     (src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:578)
  at PrestaShopBundle\Controller\Admin\Improve\ModuleController->importModuleAction()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (admin578omgxww/index.php:82)

**Comment by yiedpozi** [comment]
@faisalds Have you renamed the folder name from `Billplz-for-Prestashop-master` to `billplz` before uploading into your Prestashop store?

**Comment by faisalds** [comment]
Yes I even try to manually upload the module folder

**Comment by faisalds** [comment]
It just that Billplz rename to billplz works now. Thanks
